on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  mimics-scan-and-upload:
    name: mimics scan and upload sarif
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: rapid7/insightcloudsec-actions@v2
        with:
          api_key: ${{ secrets.ics_api_key }}
          base_url: ${{ secrets.ics_base_url }}
          config_name: cis
          target: templates/
      - name: attach scan artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mimics-scan-artifacts
          path: |
            ./mimics*.log
            ics_scan.*
      - name: upload SARIF file to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ics_scan.sarif
