on:
  push:
    branches:
      - main
jobs:
  mimics-scan:
    name: Scan and Upload
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run mimICS
        uses: rapid7/insightcloudsec-actions@latest
        with:
          api_key: ${{ secrets.ics_api_key }}
          base_url: ${{ secrets.ics_base_url }}
          config_name: AWS-CIS-1.4.0
          scan_name: Scan on Push
          target: example.yml
          driver: cft
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scan_output.sarif
