on:
  push:
    branches:
      - main

jobs:
  mimics-scan:
    name: Scan and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run mimICS
        uses: bhenderson-r7/action@main
        id: mimics
        with:
          targets: example.yml
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scan_output.sarif
