on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  mimics-scan-and-upload:
    name: mimics scan and upload sarif
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: run mimICS scan
        uses: docker://889956758113.dkr.ecr.us-east-1.amazonaws.com/bhenderson:mimics-dev
        with:
          args: --api-key ${{ secrets.ics_api_key }} --base-url ${{ secrets.ics_base_url }} scan --ics-config DemoF --report-formats sarif ./templates
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ics_scan.sarif
